CREATE DATABASE buscash;

CREATE TABLE usuarios (
	id INTEGER NOT NULL auto_increment,
	email VARCHAR(70) NOT NULL,
	CPF VARCHAR(13) NOT NULL,
	RG VARCHAR(12) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	senha VARCHAR(20)NOT NULL,
	valor_saldo DECIMAL (10,2) NOT NULL DEFAULT 10.00,
	PRIMARY KEY(id)
);